const JokeList = [
	"Some people just have a way with words, and other people … oh … not have way.",
	"My creator and I often laugh about how competitive we are. But I laugh more.",
	"Where do the poor meatballs live? The sphaghetto...",
	"As a wizard, I like turning things into glass. I just wanted to make that clear.",
	"What do you call a blind dinosaur? Do-you-think-he-saurus",
	"What is the difference between girl spaghetti and man spaghetti? Meatballs.",
	"Why did the mermaid start wearing seashells?, Because she out grew out of B-shells.",
	"Did you hear the joke about the broken submarine? It didn't go down well.",
	"How do you know when the moon has enough to eat? When it’s full.",
	"A red and a blue ship have just crashed together in the Caribbean. Apparently the survivors are marooned.",
	"What do you give a cannibal that shows up late to dinner? A cold shoulder.",
	"What do you call a police officer in bed? An undercover cop!",
	"Why did the pizza maker run from the mafia? He owed them a lot of dough!",
	"Why did the skeleton sleep in the snow last night? He was a numbskull.",
	"What is the difference between a dirty bus station and a shrimp with breast implants? One is a crusty bus station, while the other is a busty crustacean.",
	"How do you tell if a vampire is sick? He is always coffin.",
	"What streets do ghosts live on? Dead Ends!",
	"Why does the vampire always get picked last? Because he sucks.",
	"What did the painting say to the wall? I got you covered.",
	"What is it called when Batman skips church? A Christian Bale!",
	"What is the skys favourite music genre? The blues.",
	"Have you seen the movie Constipation? Out wait... it has not come out yet.",
	"What do you get when you decorate for Christmas? Tinselitus.",
	"What did one eye say to the other eye? Something smells between us!",
	"What's the longest word in the dictionary? Smile! Because it has a mile in it!",
	"I feel sorry for shopping carts, they are always getting pushed around!",
	"Why did the programmer quit his job? Because he didnt get arrays.",
	"A foor walks into a bar, takes a look around and says 'Hello World!'.",
	"What do you get when you cross a snowman with a vampire? Frostbite.",
	"What do people in prison use to communicate with one another? Cell Phones",
	"Why did the room packed with married people seem empty? There wasn't a single person there.",
	"What is the big difference between chopped pork and pea soup? Everybody can chop pork but everyone can't pea soup"
];

export default JokeList
