const quotes = [
	"But man is not made for defeat. A man can be destroyed but not defeated.",
	"When you reach the end of your rope, tie a knot in it and hang on. ",
	"There is nothing permanent except change. ",
	"You cannot shake hands with a clenched fist. ",
	"Let us sacrifice our today so that our children can have a better tomorrow.",
	"It is better to be feared than loved, if you cannot be both. ",
	"Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself. ",
	"Learning never exhausts the mind. ",
	"There is no charm equal to tenderness of heart. ",
	"All that we see or seem is but a dream within a dream. ",
	"Good judgment comes from experience, and a lot of that comes from bad judgment. ",
	"Think in the morning. Act in the noon. Eat in the evening. Sleep in the night. ",
	"Work like you don't need the money. Love like you've never been hurt. Dance like nobody's watching. ",
	"It is far better to be alone, than to be in bad company. ",
	"If you cannot do great things, do small things in a great way. ",
	"Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak. ",
	"Independence is happiness. ",
	"The supreme art of war is to subdue the enemy without fighting. ",
	"Keep your face always toward the sunshine - and shadows will fall behind you. ",
	"Being entirely honest with oneself is a good exercise. ",
	"Happiness can exist only in acceptance. ",
	"Love has no age, no limit; and no death. ",
	"You can't blame gravity for falling in love. ",
	"There is only one corner of the universe you can be certain of improving, and that's your own self. ",
	"Honesty is the first chapter in the book of wisdom. ",
	"The journey of a thousand miles begins with one step. ",
	"The best preparation for tomorrow is doing your best today. ",
	"There are two ways of spreading light: to be the candle or the mirror that reflects it. ",
	"Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better. ",
	"Coming together is a beginning; keeping together is progress; working together is success. ",
	"God gave us the gift of life; it is up to us to give ourselves the gift of living well. ",
	"Not all those who wander are lost. ",
	"Change your life today. Don't gamble on the future, act now, without delay. ",
	"I have not failed. I've just found 10,000 ways that won't work. ",
	"Whoever is happy will make others happy too. ",
	"Tell me and I forget. Teach me and I remember. Involve me and I learn. ",
	"There is nothing on this earth more to be prized than true friendship. ",
	"A leader is one who knows the way, goes the way, and shows the way. ",
	"Very little is needed to make a happy life; it is all within yourself, in your way of thinking. ",
	"If opportunity doesn't knock, build a door. ",
	"The secret of getting ahead is getting started. ",
	"Always remember that you are absolutely unique. Just like everyone else. ",
	"Wise men speak because they have something to say; Fools because they have to say something. ",
	"If your actions inspire others to dream more, learn more, do more and become more, you are a leader. ",
	"When we are no longer able to change a situation - we are challenged to change ourselves. ",
	"Problems are not stop signs, they are guidelines. ",
	"What we achieve inwardly will change outer reality. ",
	"Spread love everywhere you go. Let no one ever come to you without leaving happier. ",
	"We love life, not because we are used to living but because we are used to loving. ",
	"All our dreams can come true, if we have the courage to pursue them. ",
	"We know what we are, but know not what we may be. ",
	"It's not what you look at that matters, it's what you see.",
	"A single rose can be my garden... a single friend, my world. ",
	`Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea.
	Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. `,
	"Friends show their love in times of trouble, not in happiness. ",
	"Life is not a problem to be solved, but a reality to be experienced. ",
	"Life isn't about finding yourself. Life is about creating yourself. ",
	"The only true wisdom is in knowing you know nothing. ",
	"Everything has beauty, but not everyone sees it. ",
	"A kiss is a lovely trick designed by nature to stop speech when words become superfluous. ",
	"or it was not into my ear you whispered, but into my heart. It was not my lips you kissed, but my soul. ",
	"If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you. ",
	"As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them. ",
	"Life's most persistent and urgent question is, 'What are you doing for others?' ",
	"Believe you can and you're halfway there. ",
	"The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails. ",
	"The future belongs to those who believe in the beauty of their dreams. ",
	"Happiness resides not in possessions, and not in gold, happiness dwells in the soul. ",
	"Today you are you! That is truer than true! There is no one alive who is you-er than you! ",
	"Education is the most powerful weapon which you can use to change the world. ",
	"Change your thoughts and you change your world. ",
	"In three words I can sum up everything I've learned about life: it goes on. ",
	"Love isn't something you find. Love is something that finds you. ",
	"Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend. ",
	"Do all things with love. ",
	"Success is not final, failure is not fatal: it is the courage to continue that counts. ",
	"Do not go where the path may lead, go instead where there is no path and leave a trail. ",
	"Love is composed of a single soul inhabiting two bodies. ",
	"Where there is love there is life. ",
	"One of the most beautiful qualities of true friendship is to understand and to be understood. ",
	"The only thing necessary for the triumph of evil is for good men to do nothing. ",
	"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. ",
	"Don't judge each day by the harvest you reap but by the seeds that you plant. ",
	"Nothing is impossible, the word itself says 'I'm possible'! ",
	"Find a place inside where there's joy, and the joy will burn out the pain. ",
	"Try to be a rainbow in someone's cloud. ",
	"It is during our darkest moments that we must focus to see the light. ",
	"Keep love in your heart. A life without it is like a sunless garden when the flowers are dead. ",
	"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. ",
	"Imagination is more important than knowledge.",
	"The important thing is not to stop questioning. Curiosity has its own reason for existing.",
	"Anyone who has never made a mistake has never tried anything new.",
	"Try not to become a man of success, but rather try to become a man of value.",
	"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
	"Science without religion is lame, religion without science is blind.",
	"No problem can be solved from the same level of consciousness that created it.",
	"Everything should be made as simple as possible, but not simpler.",
	"The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.",
	"I have no special talents. I am only passionately curious."
];

export default quotes
